version: "3.9"

services:

    server:
        build:
            context: .
            dockerfile: docker/Dockerfile-server
        ports:
            - "0.0.0.0:5000:5000"
        volumes:
            - .:/app
        environment:
            - RABBITMQ_USER=${RABBITMQ_USER}
            - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
            - RABBITMQ_HOST=${RABBITMQ_HOST}
            - RABBITMQ_PORT=${RABBITMQ_PORT}
            - RABBITMQ_VHOST=${RABBITMQ_VHOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_DB_NUMBER=${REDIS_DB_NUMBER}
        depends_on:
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        restart: always
        command: ["sh", "-c", "cd engine/server && flask run --reload --host=0.0.0.0"]

    worker: 
        build:
            context: .
            dockerfile: docker/Dockerfile-worker
        volumes:
            - .:/app
        environment:
            - RABBITMQ_USER=${RABBITMQ_USER}
            - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
            - RABBITMQ_HOST=${RABBITMQ_HOST}
            - RABBITMQ_PORT=${RABBITMQ_PORT}
            - RABBITMQ_VHOST=${RABBITMQ_VHOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_DB_NUMBER=${REDIS_DB_NUMBER}
        depends_on:
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        restart: always
        command: ["sh", "-c", "celery -A engine.celery.app worker --loglevel=INFO"]

    redis:
        image: redis:alpine
        restart: always
        healthcheck:
            test: [ "CMD", "redis-cli", "ping"]
            timeout: 5s
            retries: 3
    
    rabbitmq:
        image: rabbitmq:3.10.7-management-alpine
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
            - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
        healthcheck:
            test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
            timeout: 5s
            retries: 3

    flower:
        build:
            context: .
            dockerfile: docker/Dockerfile-flower
        ports:
            - "0.0.0.0.5555:5555"
        environment:
            FLOWER_BASIC_AUTH: ${FLOWER_USER}:${FLOWER_PASSWORD}
            FLOWER_BROKER_API: http://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:15672/api/
            CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/${RABBITMQ_VHOST}
            CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB_NUMBER}
        depends_on:
            worker:
                condition: service_started
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        restart: always