version: "3.9"

services:

    server:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "127.0.0.1:5000:5000"
        volumes:
            - .:/app
        environment:
            - RABBITMQ_USER=${RABBITMQ_USER}
            - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
            - RABBITMQ_HOST=${RABBITMQ_HOST}
            - RABBITMQ_PORT=${RABBITMQ_PORT}
            - RABBITMQ_VHOST=${RABBITMQ_VHOST}
        depends_on:
            - redis
            - rabbitmq
        restart: always
        command: ["sh", "-c", "cd engine/server && flask run --reload --host=0.0.0.0"]
 
    redis:
        image: redis:alpine
        restart: always
        healthcheck:
            test: [ "CMD", "redis-cli", "ping"]
            timeout: 5s
            retries: 3
    
    rabbitmq:
        image: rabbitmq:3.10.7-management-alpine
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
            - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
        healthcheck:
            test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
            timeout: 5s
            retries: 3