FROM redis:7.0.11-alpine3.18

COPY ./docker/redis.conf /usr/local/etc/redis/redis.conf

ARG REDIS_PASSWORD=""

RUN sed -i "s/# requirepass foobared/requirepass $REDIS_PASSWORD/" /usr/local/etc/redis/redis.conf
